### ISSUE TITLE
Use tracking pixel to gather info from websites.

### ISSUE THREAD

**Issue by aidanbdh** [aidanbdh/grapevineanalytics#19]
- [x] Change user embed from script to img.

- [x] Add url form field and table data.

- [x] Handle recieved data with a GET endpoint.
